services:
  ai-service:
    build: ./ai-service
    ports:
      - "8001:8001"
    volumes:
      - ./ai-service:/app 
    environment:
      - ENV=development

#  backend:
#    build: ./backend
#    ports:
#      - "8000:8000"
#    depends_on:
#      - ai-service

#  frontend:
#    build: ./frontend
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend
